#include "tpeacock19.h"

 // START-MUGUR-REGION

 #include QMK_KEYBOARD_H
#include "version.h"


/* Macros */


/* Tap Dances */



/* Leader Keys */


/* Combos */


/* Layer Codes and Matrix */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[L_COLEMAK] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOTE, KC_A, MT(MOD_LALT, KC_R), MT(MOD_LSFT, KC_S), MT(MOD_LCTL, KC_T), KC_G, KC_M, MT(MOD_LCTL, KC_N), MT(MOD_LSFT, KC_E), MT(MOD_LALT, KC_I), KC_O, KC_Z, KC_X, KC_C, MT(MOD_LGUI, KC_D), KC_V, KC_K, MT(MOD_LGUI, KC_H), COMPAR, DOTMIN, SLSEXC, NAV_SFT, OS_MODS, MOD_SPC, SYM_RPT),

	[L_GOLD] = LAYOUT(KC_J, KC_G, KC_M, KC_P, KC_V, KC_SEMICOLON, KC_DOT, KC_SLASH, KC_DOUBLE_QUOTE, KC_QUOTE, KC_R, MT(MOD_LALT, KC_S), MT(MOD_LSFT, KC_N), MT(MOD_LCTL, KC_D), KC_B, KC_COMMA, MT(MOD_LCTL, KC_A), MT(MOD_LSFT, KC_E), MT(MOD_LALT, KC_I), KC_H, KC_X, KC_F, KC_L, MT(MOD_LGUI, KC_C), KC_W, KC_MINUS, MT(MOD_LGUI, KC_U), KC_O, KC_Y, KC_K, NAV_SFT, MOD_T, MOD_SPC, SYM_RPT),

	[L_SYM] = LAYOUT(KC_NO, LALT(KC_LEFT_ANGLE_BRACKET), KC_HASH, KC_COLON, KC_SEMICOLON, KC_EQUAL, KC_AMPERSAND, KC_AT, LALT(KC_RIGHT_ANGLE_BRACKET), KC_NO, KC_BACKSLASH, KC_QUOTE, LINCBR, LINPRN, LINBRC, KC_ASTERISK, KC_DOLLAR, LALT(KC_PERCENT), LALT(KC_EXCLAIM), KC_NO, KC_NO, KC_GRAVE, KC_NO, KC_NO, KC_NO, KC_NO, KC_CIRCUMFLEX, COMPAR, DOTMIN, SLSEXC, OSL(L_NUM), KC_TRNS, KC_NO, KC_TRNS),

	[L_NUM] = LAYOUT(KC_DOWN, KC_PLUS, KC_EQUAL, KC_AT, KC_NO, KC_NO, KC_HASH, KC_EXCLAIM, KC_PERCENT, KC_AMPERSAND, KC_6, KC_4, MT(MOD_LSFT, KC_0), KC_2, KC_UP, OSM(MOD_LSFT), KC_3, MT(MOD_LSFT, KC_1), KC_5, KC_7, KC_X, KC_DOLLAR, KC_ASTERISK, KC_8, KC_NO, KC_BSPC, KC_9, COMPAR, DOTMIN, SLSEXC, TO(0), KC_TRNS, KC_TRNS, KC_TRNS),

	[L_MODS] = LAYOUT(KC_NO, XWBAK, KC_PAGE_DOWN, LCTL(LSFT(KC_TAB)), KC_NO, KC_NO, LCTL(KC_TAB), KC_PAGE_UP, XWFWD, KC_NO, OSL(L_SWNAV), OSM(MOD_LALT), OSM(MOD_LSFT), OSM(MOD_LCTL), XREDO, KC_DELETE, OSM(MOD_LCTL), OSM(MOD_LSFT), OSM(MOD_LALT), OSL(L_MEDIA), XUNDO, XCUT, XCOPY, OSM(MOD_LGUI), XPAST, KC_BSPC, OSM(MOD_LGUI), KC_ESCAPE, KC_TAB, LLOCK, TO(0), KC_TRNS, KC_ENTER, SWAPKEY),

	[L_NAV] = LAYOUT(KC_NO, XWBAK, KC_MS_UP, LCTL(LSFT(KC_TAB)), KC_NO, KC_NO, LCTL(KC_TAB), KC_NO, XWFWD, BASETOGG, KC_NO, KC_MS_LEFT, KC_MS_DOWN, KC_MS_RIGHT, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, TO(L_EMACS), TG_WIN, KC_MS_WH_LEFT, KC_MS_WH_UP, KC_MS_WH_DOWN, KC_MS_WH_RIGHT, KC_NO, KC_MS_BTN1, KC_MS_BTN2, KC_APPLICATION, TG_LIN, TO(0), KC_TRNS, LLOCK, OSL(L_WNAV)),

	[L_WNAV] = LAYOUT(XCLOSE, XWBAK, LGUI(KC_F), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, XWFWD, KC_NO, G(KC_6), G(KC_4), G(KC_0), G(KC_2), LGUI(KC_RIGHT), LGUI(KC_LEFT), G(KC_3), G(KC_1), G(KC_5), G(KC_7), G(KC_L), KC_NO, LGUI(KC_N), G(KC_8), G(KC_EQL), G(KC_MINS), G(KC_9), LGUI(KC_E), XWTOG, KC_NO, TO(0), KC_TRNS, XSRCH, G(KC_TAB)),

	[L_SWNAV] = LAYOUT(XCLOSE, XWBAK, LGUI(KC_F), KC_NO, KC_NO, KC_NO, KC_NO, LGUI(LSFT(KC_U)), XWFWD, KC_NO, S(G(KC_6)), S(G(KC_4)), S(G(KC_0)), S(G(KC_2)), S(G(KC_RIGHT)), S(G(KC_LEFT)), S(G(KC_3)), S(G(KC_1)), S(G(KC_5)), S(G(KC_7)), G(KC_L), XWMOVL, KC_N, S(G(KC_8)), G(KC_EQL), G(KC_MINS), S(G(KC_9)), KC_E, XWMOV, KC_NO, TO(0), KC_TRNS, S(G(KC_SPC)), S(G(KC_TAB))),

	[L_MEDIA] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_BRIGHTNESS_DOWN, KC_BRIGHTNESS_UP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LALT, KC_LGUI, KC_LCTL, KC_NO, KC_AUDIO_MUTE, KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, KC_MS_BTN1, KC_MS_BTN2, KC_MS_WH_RIGHT, KC_F20, TO(0), KC_TRNS, KC_ENTER, TO(L_FUNC)),

	[L_FUNC] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F6, KC_F4, KC_NO, KC_F2, KC_NO, KC_NO, KC_F3, KC_F1, KC_F5, KC_F7, KC_NO, KC_F12, KC_F10, KC_F8, KC_NO, KC_NO, KC_F9, KC_F11, KC_NO, KC_NO, TO(0), KC_TRNS, KC_NO, MYRESET),

	[L_EMACS] = LAYOUT(LCTL(KC_G), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, REPEAT, KC_TAB, KC_NO, LCTL(LALT(KC_R)), LCTL(LALT(KC_T)), LCTL(KC_G), LCTL(LALT(KC_SPACE)), LCTL(LALT(KC_F)), LCTL(LALT(KC_B)), LCTL(LALT(LGUI(KC_U))), KC_ENTER, LALT(KC_X), KC_NO, LALT(KC_MINUS), LCTL(LALT(KC_K)), KC_NO, LCTL(LALT(KC_U)), LCTL(LALT(KC_D)), LCTL(KC_LEFT_ANGLE_BRACKET), LCTL(KC_RIGHT_ANGLE_BRACKET), LCTL(LALT(KC_E)), TO(0), KC_TRNS, KC_NO, REPEAT)
};

/* Per Key Tapping Terms */
 

// END-MUGUR-REGION           
